{
 "title": "Infraestrutura Kubernetes - Node Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Origem dos Dados", "query": "prometheus" },
   {
    "name": "job",
    "label": "Tarefa",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nome do Nó",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instância",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\",nodename=~\"${nodename:regex}\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resumo Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resumo dos recursos",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_pressure_cpu_waiting_seconds_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(rate(node_pressure_memory_waiting_seconds_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Memória"
    },
    {
     "expr": "avg(rate(node_pressure_io_waiting_seconds_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Disco"
    }
   ]
  },
  {
   "title": "Uso da CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\",job=\"$job\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Memória utilizada",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (sum(node_memory_MemAvailable_bytes{instance=~\"$node\",job=\"$job\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}))) * 100, 0)"
    }
   ]
  },
  {
   "title": "Uso de swap",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"}) > bool 0) * (1 - (sum(node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\"}) / clamp_min(sum(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"}), 1))) * 100"
    }
   ]
  },
  {
   "title": "Nós na visualização",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\",instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo em atividade",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_time_seconds{instance=~\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Núcleos de CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count by (instance) (node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Swap total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"})"
    }
   ]
  },
  { "title": "Detalhado", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Uso da CPU por estado",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",mode=\"system\"}[$__rate_interval]))",
     "legendFormat": "Sistema"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",mode=\"user\"}[$__rate_interval]))",
     "legendFormat": "Usuário"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "Espera de E/S"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Ociosa"
    }
   ]
  },
  {
   "title": "Uso de memória",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "Em uso"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "Disponível"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$node\",job=\"$job\",device=\"eth0\"}[$__rate_interval])) * 8",
     "legendFormat": "Recebimento"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\",device=\"eth0\"}[$__rate_interval])) * 8",
     "legendFormat": "Envio"
    }
   ]
  },
  {
   "title": "Uso do disco (/var)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/var\"} - node_filesystem_avail_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/var\"}) / node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/var\"}) * 100)",
     "legendFormat": "Maior uso em /var"
    }
   ]
  }
 ]
}