# Conf padrão do Telegraf: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2_agent/examples/tomcat.conf
[agent]
  interval = "15s" # Consulta a cada 15s
  round_interval = true 
  flush_interval = "15s" # Envia a cada 15s
  omit_hostname = true
  skip_processors_after_aggregators = true
  
[[inputs.jolokia2_agent]]
  urls = ["${JOLOKIA_URL}"]
  username = "${JOLOKIA_USER}"
  password = "${JOLOKIA_PASSWORD}"
  response_timeout = "5s" # Caso alguma consulta passe +5s, será descartada
  name_prefix = "tomcat_"

  [[inputs.jolokia2_agent.metric]]
    name = "operating_system"
    mbean = "java.lang:type=OperatingSystem"
    # Abaixo as infos que serão coletadas do MBean
    paths = [
      "AvailableProcessors",
      "ProcessCpuLoad",
      "SystemCpuLoad",
      "SystemLoadAverage",
      "ProcessCpuTime"
    ]

  [[inputs.jolokia2_agent.metric]]
    name = "jvm_runtime"
    mbean = "java.lang:type=Runtime"
    paths = ["Uptime"]

  [[inputs.jolokia2_agent.metric]]
    name = "jvm_memory"
    mbean = "java.lang:type=Memory"
    paths = [
      "HeapMemoryUsage",
      "NonHeapMemoryUsage",
      "ObjectPendingFinalizationCount"
    ]

  [[inputs.jolokia2_agent.metric]]
    name = "jvm_garbage_collector"
    mbean = "java.lang:name=*,type=GarbageCollector"
    paths = ["CollectionTime", "CollectionCount"]
    tag_keys = ["name"]

  [[inputs.jolokia2_agent.metric]]
    name = "jvm_memory_pool"
    mbean = "java.lang:name=*,type=MemoryPool"
    paths = ["Usage", "PeakUsage", "CollectionUsage"]
    tag_keys = ["name"]
    tag_prefix = "pool_"

  [[inputs.jolokia2_agent.metric]]
    name = "tomcat_requests"
    mbean = "Catalina:name=*,type=GlobalRequestProcessor"
    paths = [
      "requestCount",
      "errorCount",
      "processingTime",
      "bytesReceived",
      "bytesSent"
    ]
    tag_keys = ["name"]

  [[inputs.jolokia2_agent.metric]]
    name = "tomcat_threads"
    mbean = "Catalina:name=*,type=ThreadPool"
    paths = ["maxThreads", "currentThreadCount", "currentThreadsBusy"]
    tag_keys = ["name"]

[[outputs.prometheus_client]]
  listen = ":9273" # Vai ouvir na porta 9273
  path = "/metrics" # Endpoint para o Prometheus
  expiration_interval = "60s"
  collectors_exclude = ["gocollector", "process"]