apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-datasource
    files:
      - datasource.yaml=datasource.yaml

  - name: grafana-dashboard-provider
    files:
      - dashboards.yaml=provisioning/dashboards/dashboards.yaml

  - name: grafana-dashboards
    files:
      - infraestrutura.json=dashboards/infraestrutura.json
      - jenkins-tomcat.json=dashboards/jenkins-tomcat.json

  - name: grafana-alert-rules
    files:
      - alert-rules.yaml=provisioning/alerting/alert-rules.yaml

secretGenerator:
  - name: grafana-credentials
    envs:
      - .env